### ISSUE TITLE
What happened to hugo-plain-theme?

### ISSUE THREAD

**Issue by Darthagnon** [hiAndrewQuinn/resorter#1]
I noticed you recently deleted your hugo-plain-theme https://web.archive.org/web/20221120022803/https://github.com/hiAndrewQuinn/hugo-plain-theme/... why 😥?

I restored a local copy I had (13-11-2022) to a fork: https://github.com/Darthagnon/hugo-plain-theme - were there any changes you made after that, that I should restore?

**Comment by hiAndrewQuinn** [comment]
Can't believe I never followed up on this - **https://github.com/hiAndrewQuinn/minimum-viable-hugo** is the modern version!
